# This is your main playbook you will run with:
# ansible-playbook site.yml
# You can kick off everything from this playbook.
# Or, you can create separate playbooks in this directory for specific orchestration events.

---
- name: apply common configuration to all nodes
  hosts: localhost
  user: dev

  roles:
    - common

  vars:
    slac_sites:
      esh: 
        site_name: esh-elog
        repo: "https://github.com/slac/ESH-Field-E-Log"
        path: /tmp/